/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://6icb7oflxrefzh7qzibdbshyu4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ogyg27sx5vcafmodv4c2zailhi",
    "aws_cognito_identity_pool_id": "us-west-2:6deccdf4-d3c3-4837-903c-ad7a17dc2293",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5niwzhd99",
    "aws_user_pools_web_client_id": "49tbbt5gebg0h48v9rcah66rjj",
    "oauth": {},
    "aws_user_files_s3_bucket": "ec-site-bucket133728-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
